<?xml version="1.0" encoding="UTF-8"?><testrun name="MyAssertTest" project="junit_in_5_steps" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="com.in28minutes.junit.MyAssertTest" time="0.021" displayname="MyAssertTest" uniqueid="[engine:junit-jupiter]/[class:com.in28minutes.junit.MyAssertTest]">
    <testcase name="test" classname="com.in28minutes.junit.MyAssertTest" time="0.021" displayname="test()" uniqueid="[engine:junit-jupiter]/[class:com.in28minutes.junit.MyAssertTest]/[method:test()]">
      <failure>
        <expected>2</expected>
        <actual>3</actual>
        org.opentest4j.AssertionFailedError: failure message ==&gt; expected: &lt;2&gt; but was: &lt;3&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:563)&#13;
	at com.in28minutes.junit.MyAssertTest.test(MyAssertTest.java:21)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
